version: '3.8'

services:
  db:
    image: mysql:8.0 # You can specify a different version if needed
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: .@p92m18r. # Replace with a strong password
      MYSQL_DATABASE: atribui # Optional: Create a default database
    ports:
      - "3306:3306" # Map host port 3306 to container port 3306
    volumes:
      - mysql_data:/var/lib/mysql # Persist data using a named volume

volumes:
  mysql_data:
    driver: local